version: "3"

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}