import { PrimaryColumn } from 'typeorm';
import { BaseEntityInput } from './BaseEntity.input';

export abstract class BaseEntity {
  // id is generated by the clients since they may work offline.
  // therefore we cannot use PrimaryGeneratedColumn
  @PrimaryColumn({ type: 'int' })
  id: number;

  constructor(baseEntity?: BaseEntityInput) {
    if (baseEntity) {
      if (baseEntity.id != null) this.id = baseEntity.id;
    }
  }
}
